### ISSUE TITLE
Express routes

### ISSUE THREAD

**Issue by aHumanBeing** [johanan/Where-to-eat#5]
Is there anyway to use the socket.js file from other routes? On my login form, users also select a location from a drop down list.  In another route (/local), this location will be used as a room to join in socket.io.  Basically, I want to join the room when a user goes to the /local route and then populate results from redis via socket.io.  Hopefully I explained that clearly.

Thanks

**Comment by aHumanBeing** [comment]
I was able to accomplish this by joining the particular namespace from the client side.

**Comment by johanan** [comment]
I was going to tell you that socket.io connections are not bound at the route level. Socket.io connects to the server and all routing is done there.

**Comment by aHumanBeing** [comment]
I appreciate it Johanan.  Your guide has been very helpful for me and I've referred others to it already.  
I'm wondering if you ever had to deal with saving the socket id for anything.  My app is up and running but when users perform actions, I want to save what they have done so others can message them later on if needed.  It's tricky because I have several routes and the socket disconnects and reconnects between the routes.
