### ISSUE TITLE
demo broken

### ISSUE THREAD

**Issue by gad2103** [johanan/Where-to-eat#6]
mixed content is causing the socket and map functionality to fail on the demo. would be nice to see it working!

**Comment by johanan** [comment]
I will have to update a few files, but in the meantime you should be able to see the demo working at: http://thawing-cliffs-6040.herokuapp.com/

**Comment by johanan** [comment]
I was able to fix this with commit ca180ca895272769dc71c2a24ffbd9619e1bb3a7. The tiles throw a warning, but the demo does work now.

**Comment by gad2103** [comment]
Thanks!
